name: inventory_management_system_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.14
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  nb_utils: ^7.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
